// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var S$RescriptStruct = require("rescript-struct/src/S.js");

var myStringStruct = S$RescriptStruct.string(undefined);

var myIntStruct = S$RescriptStruct.$$int(undefined);

var myFloatStruct = S$RescriptStruct.$$float(undefined);

var myBoolStruct = S$RescriptStruct.bool(undefined);

var myUnitStruct = S$RescriptStruct.unit(undefined);

var myUnknownStruct = S$RescriptStruct.unknown(undefined);

var myNeverStruct = S$RescriptStruct.never(undefined);

var myOptionOfStringStruct = S$RescriptStruct.option(S$RescriptStruct.string(undefined));

var myArrayOfStringStruct = S$RescriptStruct.array(S$RescriptStruct.string(undefined));

var myListOfStringStruct = S$RescriptStruct.list(S$RescriptStruct.string(undefined));

var myDictOfString1Struct = S$RescriptStruct.dict(S$RescriptStruct.string(undefined));

var myDictOfString2Struct = S$RescriptStruct.dict(S$RescriptStruct.string(undefined));

var myJsonable1Struct = S$RescriptStruct.jsonable(undefined);

var myJsonable2Struct = S$RescriptStruct.jsonable(undefined);

var myResultStruct = S$RescriptStruct.result(S$RescriptStruct.$$int(undefined), S$RescriptStruct.string(undefined));

var myTupleStruct = S$RescriptStruct.Tuple.factory([
      S$RescriptStruct.string(undefined),
      S$RescriptStruct.$$int(undefined)
    ]);

var myBigTupleStruct = S$RescriptStruct.Tuple.factory([
      S$RescriptStruct.string(undefined),
      S$RescriptStruct.string(undefined),
      S$RescriptStruct.string(undefined),
      S$RescriptStruct.$$int(undefined),
      S$RescriptStruct.$$int(undefined),
      S$RescriptStruct.$$int(undefined),
      S$RescriptStruct.$$float(undefined),
      S$RescriptStruct.$$float(undefined),
      S$RescriptStruct.$$float(undefined),
      S$RescriptStruct.bool(undefined),
      S$RescriptStruct.bool(undefined),
      S$RescriptStruct.bool(undefined)
    ]);

var myCustomStringStruct = S$RescriptStruct.$$String.email(S$RescriptStruct.string(undefined), undefined, undefined);

exports.myStringStruct = myStringStruct;
exports.myIntStruct = myIntStruct;
exports.myFloatStruct = myFloatStruct;
exports.myBoolStruct = myBoolStruct;
exports.myUnitStruct = myUnitStruct;
exports.myUnknownStruct = myUnknownStruct;
exports.myNeverStruct = myNeverStruct;
exports.myOptionOfStringStruct = myOptionOfStringStruct;
exports.myArrayOfStringStruct = myArrayOfStringStruct;
exports.myListOfStringStruct = myListOfStringStruct;
exports.myDictOfString1Struct = myDictOfString1Struct;
exports.myDictOfString2Struct = myDictOfString2Struct;
exports.myJsonable1Struct = myJsonable1Struct;
exports.myJsonable2Struct = myJsonable2Struct;
exports.myResultStruct = myResultStruct;
exports.myTupleStruct = myTupleStruct;
exports.myBigTupleStruct = myBigTupleStruct;
exports.myCustomStringStruct = myCustomStringStruct;
/* myStringStruct Not a pure module */
