// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Core__JSON = require("@rescript/core/src/Core__JSON.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Core__Result = require("@rescript/core/src/Core__Result.js");

function falseableEncode(encoder, opt) {
  if (opt !== undefined) {
    return Curry._1(encoder, Caml_option.valFromOption(opt));
  } else {
    return false;
  }
}

function falseableDecode(decoder, json) {
  var match = Core__JSON.Decode.bool(json);
  if (match !== undefined && !match) {
    return {
            TAG: /* Ok */0,
            _0: undefined
          };
  }
  var __x = Curry._1(decoder, json);
  return Core__Result.map(__x, (function (v) {
                return Caml_option.some(v);
              }));
}

var falseable = [
  falseableEncode,
  falseableDecode
];

function magicDecode(j) {
  return {
          TAG: /* Ok */0,
          _0: j
        };
}

function magic_0(prim) {
  return prim;
}

var magic = [
  magic_0,
  magicDecode
];

exports.falseableEncode = falseableEncode;
exports.falseableDecode = falseableDecode;
exports.falseable = falseable;
exports.magicDecode = magicDecode;
exports.magic = magic;
/* No side effect */
