// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../src/S.res.mjs";
import * as Sury from "sury";
import * as Vitest from "./Vitest.res.mjs";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let noopOpCode = S.compileConvertOrThrow(Sury.unknown, undefined, Sury.unknown).toString();

function throwError(error) {
  throw error;
}

function fail(message, pathOpt) {
  let path = pathOpt !== undefined ? pathOpt : S.Path.empty;
  throw new Sury.Error({
    code: "invalid_input",
    path: path,
    reason: message,
    expected: Sury.unknown,
    received: Sury.unknown
  });
}

function unsafeGetVariantPayload(variant) {
  return variant._0;
}

let Test = /* @__PURE__ */Primitive_exceptions.create("U.Test");

function throwTestException() {
  throw {
    RE_EXN_ID: Test,
    Error: new Error()
  };
}

function assertThrowsTestException(t, fn, message) {
  try {
    fn();
    return Vitest.Assert.fail(t, "Didn't throw");
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === Test) {
      return Vitest.Assert.pass(t, message);
    } else {
      return Vitest.Assert.fail(t, "Thrown another exception");
    }
  }
}

function assertThrows(t, cb, errorPayload) {
  let any;
  try {
    any = cb();
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === S.Exn) {
      return Vitest.Assert.is(t, exn._1.message, new Sury.Error(errorPayload).message, undefined);
    }
    throw exn;
  }
  Vitest.Assert.fail(t, "Asserted result is not Error. Recieved: " + JSON.stringify(any));
}

function assertThrowsMessage(t, cb, errorMessage, message) {
  let any;
  try {
    any = cb();
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === S.Exn) {
      return Vitest.Assert.is(t, exn._1.message, errorMessage, message);
    }
    throw exn;
  }
  Vitest.Assert.fail(t, `Asserted result is not S.Exn "` + errorMessage + `". Instead got: ` + JSON.stringify(any));
}

async function asyncAssertThrowsMessage(t, cb, errorMessage, message) {
  let any;
  try {
    any = await cb();
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === S.Exn) {
      return Vitest.Assert.is(t, exn._1.message, errorMessage, message);
    }
    throw exn;
  }
  return Vitest.Assert.fail(t, `Asserted result is not S.Exn "` + errorMessage + `". Instead got: ` + JSON.stringify(any));
}

function getCompiledCodeString(schema, op, embedded) {
  let toFn = schema => {
    if (op === "Parse") {
      return S.compileConvertOrThrow(Sury.unknown, undefined, schema);
    } else if (op === "EncodeToJson") {
      return S.compileConvertOrThrow(schema, undefined, Sury.json);
    } else if (op === "Convert") {
      return S.compileConvertOrThrow(Sury.reverse(schema), undefined, Sury.unknown);
    } else if (op === "Assert") {
      return S.compileConvertOrThrow(Sury.unknown, undefined, S.to(schema, Sury.noValidation(Sury.literal(), true), undefined));
    } else if (op === "EncodeAsync") {
      return S.compileConvertAsyncOrThrow(schema, undefined, Sury.unknown);
    } else if (op === "ReverseParse") {
      return S.compileConvertOrThrow(Sury.unknown, undefined, Sury.reverse(schema));
    } else if (op === "ConvertAsync") {
      return S.compileConvertAsyncOrThrow(Sury.reverse(schema), undefined, Sury.unknown);
    } else if (op === "Encode") {
      return S.compileConvertOrThrow(schema, undefined, Sury.unknown);
    } else {
      return S.compileConvertAsyncOrThrow(Sury.unknown, undefined, schema);
    }
  };
  let fn = toFn(schema);
  let code = {
    contents: fn.toString()
  };
  if (embedded !== undefined) {
    embedded.forEach(param => {
      code.contents = code.contents + "\n" + (param[0] + `: ` + fn.embedded[param[1]]);
    });
  } else {
    let defs = schema.$defs;
    if (defs !== undefined && code.contents !== noopOpCode) {
      Stdlib_Dict.forEachWithKey(defs, (schema, key) => {
        try {
          let defFn = toFn(schema);
          code.contents = code.contents + "\n" + (key + `: ` + defFn.toString());
          return;
        } catch (_exn) {
          return;
        }
      });
    }
  }
  return code.contents;
}

function cleanUpSchema(schema) {
  let $$new = {};
  Object.entries(schema).forEach(param => {
    let value = param[1];
    let key = param[0];
    switch (key) {
      case "hasTransform" :
      case "isAsync" :
      case "k" :
      case "of" :
      case "output" :
      case "p" :
      case "r" :
      case "seq" :
        return;
      default:
        if (typeof value === "function") {
          return;
        } else {
          if (typeof value === "object" && value !== null) {
            $$new[key] = cleanUpSchema(value);
          } else {
            $$new[key] = value;
          }
          return;
        }
    }
  });
  return $$new;
}

function unsafeAssertEqualSchemas(t, s1, s2, message) {
  Vitest.Assert.unsafeDeepEqual(t, cleanUpSchema(s1), cleanUpSchema(s2), message);
}

function assertCompiledCode(t, schema, op, code, embedded, message) {
  Vitest.Assert.is(t, getCompiledCodeString(schema, op, embedded), code, message);
}

function assertCompiledCodeIsNoop(t, schema, op, message) {
  assertCompiledCode(t, schema, op, noopOpCode, undefined, message);
}

function assertReverseParsesBack(t, schema, value) {
  Vitest.Assert.unsafeDeepEqual(t, S.parseOrThrow(S.convertOrThrow(value, schema, undefined, Sury.unknown), schema), value, undefined);
}

function assertReverseReversesBack(t, schema) {
  unsafeAssertEqualSchemas(t, schema, Sury.reverse(Sury.reverse(schema)), undefined);
}

let assertEqualSchemas = unsafeAssertEqualSchemas;

export {
  noopOpCode,
  throwError,
  fail,
  unsafeGetVariantPayload,
  Test,
  throwTestException,
  assertThrowsTestException,
  assertThrows,
  assertThrowsMessage,
  asyncAssertThrowsMessage,
  getCompiledCodeString,
  cleanUpSchema,
  unsafeAssertEqualSchemas,
  assertCompiledCode,
  assertCompiledCodeIsNoop,
  assertEqualSchemas,
  assertReverseParsesBack,
  assertReverseReversesBack,
}
/* noopOpCode Not a pure module */
