// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";

let Async = {};

function asyncTest(prim0, prim1) {
  Vitest.test(prim0, prim1);
}

function plan(t, n) {
  t.expect.assertions(n);
}

let ExecutionContext = {
  plan: plan
};

function deepEqual(t, actual, expected, param) {
  t.expect(actual).toEqual(expected);
}

function unsafeDeepEqual(t, actual, expected, param) {
  t.expect(actual).toEqual(expected);
}

function notDeepEqual(t, actual, expected, param) {
  t.expect(actual).not.toEqual(expected);
}

function is(t, actual, expected, param) {
  t.expect(actual).toBe(expected);
}

function not(t, actual, expected, param) {
  t.expect(actual).not.toBe(expected);
}

function pass(_t, param) {
  
}

function fail(t, message) {
  t.expect.fail(message);
}

function throws(t, fn, expectationsOpt, param) {
  let expectations = expectationsOpt !== undefined ? expectationsOpt : ({});
  let msg = expectations.message;
  if (msg !== undefined) {
    return t.expect(fn).toThrowError(msg);
  } else {
    return t.expect(fn).toThrow();
  }
}

function notThrows(t, fn, param) {
  t.expect(fn).not.toThrow();
}

let Assert = {
  deepEqual: deepEqual,
  unsafeDeepEqual: unsafeDeepEqual,
  notDeepEqual: notDeepEqual,
  is: is,
  not: not,
  pass: pass,
  fail: fail,
  throws: throws,
  notThrows: notThrows
};

export {
  Async,
  asyncTest,
  ExecutionContext,
  Assert,
}
/* vitest Not a pure module */
