// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.res.mjs";
import Ava from "ava";
import * as S$RescriptSchema from "rescript-schema/src/S.res.mjs";

let polySchema = S$RescriptSchema.union([
  S$RescriptSchema.literal("one"),
  S$RescriptSchema.literal("two")
]);

Ava("Polymorphic variant", t => U.assertEqualSchemas(t, polySchema, S$RescriptSchema.union([
  S$RescriptSchema.literal("one"),
  S$RescriptSchema.literal("two")
]), undefined));

let polyWithSingleItemSchema = S$RescriptSchema.literal("single");

Ava("Polymorphic variant with single item becomes a literal schema of the item", t => U.assertEqualSchemas(t, polyWithSingleItemSchema, S$RescriptSchema.literal("single"), undefined));

let polyEmbededSchema = S$RescriptSchema.shape(S$RescriptSchema.string, param => "one");

Ava("Embed custom schema for polymorphic variants", t => U.assertEqualSchemas(t, polyEmbededSchema, S$RescriptSchema.shape(S$RescriptSchema.string, param => "one"), undefined));

let dictFieldSchema = S$RescriptSchema.dict(S$RescriptSchema.literal("one"));

Ava("Supported as a dict field", t => U.assertEqualSchemas(t, dictFieldSchema, S$RescriptSchema.dict(S$RescriptSchema.literal("one")), undefined));

let recordFieldSchema = S$RescriptSchema.schema(s => ({
  poly: s.m(S$RescriptSchema.literal("one"))
}));

Ava("Supported as a record field", t => U.assertEqualSchemas(t, recordFieldSchema, S$RescriptSchema.object(s => ({
  poly: s.f("poly", S$RescriptSchema.literal("one"))
})), undefined));

let objectFieldSchema = S$RescriptSchema.schema(s => ({
  poly: s.m(S$RescriptSchema.literal("one"))
}));

Ava("Supported as a object field", t => U.assertEqualSchemas(t, objectFieldSchema, S$RescriptSchema.object(s => ({
  poly: s.f("poly", S$RescriptSchema.literal("one"))
})), undefined));

export {
  polySchema,
  polyWithSingleItemSchema,
  polyEmbededSchema,
  dictFieldSchema,
  recordFieldSchema,
  objectFieldSchema,
}
/* polySchema Not a pure module */
