// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.bs.mjs";
import Ava from "ava";
import * as S$RescriptStruct from "rescript-struct/src/S.bs.mjs";

var polyStruct = S$RescriptStruct.union([
      S$RescriptStruct.literal("one"),
      S$RescriptStruct.literal("two")
    ]);

Ava("Polymorphic variant", (function (t) {
        U.assertEqualStructs(t, polyStruct, S$RescriptStruct.union([
                  S$RescriptStruct.literal("one"),
                  S$RescriptStruct.literal("two")
                ]), undefined);
      }));

var polyWithSingleItemStruct = S$RescriptStruct.literal("single");

Ava("Polymorphic variant with single item becomes a literal struct of the item", (function (t) {
        U.assertEqualStructs(t, polyWithSingleItemStruct, S$RescriptStruct.literal("single"), undefined);
      }));

var polyWithAliasStruct = S$RescriptStruct.union([
      S$RescriptStruct.literal("one"),
      S$RescriptStruct.literal("two")
    ]);

Ava("Polymorphic variant with partial @as usage", (function (t) {
        U.assertEqualStructs(t, polyWithAliasStruct, S$RescriptStruct.union([
                  S$RescriptStruct.literal("one"),
                  S$RescriptStruct.literal("two")
                ]), undefined);
      }));

export {
  polyStruct ,
  polyWithSingleItemStruct ,
  polyWithAliasStruct ,
}
/* polyStruct Not a pure module */
