// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "../../../../src/S.bs.mjs";
import Ava from "ava";
import * as TestUtils from "../utils/TestUtils.bs.mjs";

Ava("Creates struct with the name struct from t type", (function (t) {
        TestUtils.assertEqualStructs(t, S.string, S.string, undefined, undefined);
      }));

Ava("Creates struct with the type name and struct at the for non t types", (function (t) {
        TestUtils.assertEqualStructs(t, S.$$int, S.$$int, undefined, undefined);
      }));

var reusedTypesStruct = S.tuple(function (s) {
      return [
              s.i(0, S.string),
              s.i(1, S.$$int),
              s.i(2, S.bool),
              s.i(3, S.$$float)
            ];
    });

Ava("Can reuse structs from other types", (function (t) {
        TestUtils.assertEqualStructs(t, reusedTypesStruct, S.tuple(function (s) {
                  return [
                          s.i(0, S.string),
                          s.i(1, S.$$int),
                          s.i(2, S.bool),
                          s.i(3, S.$$float)
                        ];
                }), undefined, undefined);
      }));

var struct = S.string;

var fooStruct = S.$$int;

export {
  struct ,
  fooStruct ,
  reusedTypesStruct ,
}
/*  Not a pure module */
