// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let empty = [];

let Path = {
  empty: empty
};

let Exn = /* @__PURE__ */Primitive_exceptions.create("S.Exn");

Sury.$setExnId(Exn);

let none = 0;

let async = 1;

let Flag = {
  none: none,
  async: async
};

let $$Error = {};

function refine(schema, refiner, error, path) {
  return Sury.refine(schema, refiner, {
    error: error,
    path: path
  });
}

function unwrapConversion(conversion) {
  if (typeof conversion !== "object") {
    return conversion;
  } else if (conversion.TAG === "Sync") {
    return conversion._0;
  } else {
    return {
      async: conversion._0
    };
  }
}

function to(from, target, custom) {
  if (custom !== undefined) {
    return Sury.to(from, target, {
      decodeToOutput: unwrapConversion(custom.decode),
      encodeFromOutput: unwrapConversion(custom.encode)
    });
  } else {
    return Sury.to(from, target);
  }
}

function compileConvertOrThrow(from, via, to) {
  if (via !== undefined) {
    return Sury.encodeOrThrow(from, via, to);
  } else {
    return Sury.encodeOrThrow(from, to);
  }
}

function compileConvertAsPromiseOrReject(from, via, to) {
  if (via !== undefined) {
    return Sury.encodeAsPromiseOrReject(from, via, to);
  } else {
    return Sury.encodeAsPromiseOrReject(from, to);
  }
}

function compileConvertAsResult(from, via, to) {
  if (via !== undefined) {
    return Sury.$encodeAsResult(from, via, to);
  } else {
    return Sury.$encodeAsResult(from, to);
  }
}

function compileConvertAsResultPromise(from, via, to) {
  if (via !== undefined) {
    return Sury.$encodeAsResultPromise(from, via, to);
  } else {
    return Sury.$encodeAsResultPromise(from, to);
  }
}

function parseOrThrow(any, to) {
  return Sury.parseOrThrow(to)(any);
}

function parseAsPromiseOrReject(any, to) {
  return Sury.parseAsPromiseOrReject(to)(any);
}

function parseAsResult(any, to) {
  return Sury.$parseAsResult(to)(any);
}

function parseAsResultPromise(any, to) {
  return Sury.$parseAsResultPromise(to)(any);
}

function isInput(any, to) {
  return Sury.isInput(to)(any);
}

function isOutput(any, schema) {
  return Sury.isOutput(schema)(any);
}

function convertOrThrow(any, from, via, to) {
  return compileConvertOrThrow(from, via, to)(any);
}

function convertAsPromiseOrReject(any, from, via, to) {
  return compileConvertAsPromiseOrReject(from, via, to)(any);
}

function convertAsResult(any, from, via, to) {
  return compileConvertAsResult(from, via, to)(any);
}

function convertAsResultPromise(any, from, via, to) {
  return compileConvertAsResultPromise(from, via, to)(any);
}

function makeOrThrow(value, schema) {
  return Sury.makeOutputOrThrow(schema)(value);
}

function makeAsPromiseOrReject(value, schema) {
  return Sury.makeOutputAsPromiseOrReject(schema)(value);
}

function makeAsResult(value, schema) {
  return Sury.$makeAsResult(schema)(value);
}

function makeAsResultPromise(value, schema) {
  return Sury.$makeAsResultPromise(schema)(value);
}

let Schema = {};

let $$Object = {};

let Tuple = {};

function tuple1(v0) {
  return Sury.tuple(s => s.item(0, v0));
}

function tuple2(v1, v2) {
  return Sury.schema([
    v1,
    v2
  ]);
}

function tuple3(v1, v2, v3) {
  return Sury.schema([
    v1,
    v2,
    v3
  ]);
}

let Option = {};

let Id = {};

let Metadata = {
  Id: Id
};

function fromJSONSchema(jsonSchema) {
  return Sury.fromJSONSchema(jsonSchema);
}

export {
  Path,
  Exn,
  Flag,
  $$Error,
  refine,
  to,
  compileConvertOrThrow,
  compileConvertAsPromiseOrReject,
  compileConvertAsResult,
  compileConvertAsResultPromise,
  parseOrThrow,
  parseAsPromiseOrReject,
  parseAsResult,
  parseAsResultPromise,
  isInput,
  isOutput,
  convertOrThrow,
  convertAsPromiseOrReject,
  convertAsResult,
  convertAsResultPromise,
  makeOrThrow,
  makeAsPromiseOrReject,
  makeAsResult,
  makeAsResultPromise,
  Schema,
  $$Object,
  Tuple,
  tuple1,
  tuple2,
  tuple3,
  Option,
  Metadata,
  fromJSONSchema,
}
/*  Not a pure module */
