// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$RescriptStruct from "rescript-struct/src/S.bs.mjs";

var t1Struct = S$RescriptStruct.union([
      S$RescriptStruct.literalVariant({
            TAG: /* String */0,
            _0: "하나"
          }, "one"),
      S$RescriptStruct.literalVariant({
            TAG: /* String */0,
            _0: "둘"
          }, "two")
    ]);

var t2Struct = S$RescriptStruct.union([
      S$RescriptStruct.literalVariant({
            TAG: /* String */0,
            _0: "one"
          }, "one"),
      S$RescriptStruct.literalVariant({
            TAG: /* String */0,
            _0: "two"
          }, "two")
    ]);

var t3Struct = S$RescriptStruct.literalVariant({
      TAG: /* String */0,
      _0: "single"
    }, "single");

export {
  t1Struct ,
  t2Struct ,
  t3Struct ,
}
/* t1Struct Not a pure module */
