// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.bs.mjs";
import * as S$RescriptStruct from "rescript-struct/src/S.bs.mjs";

var error = U.error({
      operation: "Parsing",
      code: {
        TAG: "OperationFailed",
        _0: "Something went wrong"
      },
      path: S$RescriptStruct.Path.empty
    });

var stringStruct = S$RescriptStruct.string;

export {
  stringStruct ,
  error ,
}
/* error Not a pure module */
