// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.bs.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.bs.mjs";

var error = U.error({
      operation: "Parsing",
      code: {
        TAG: "OperationFailed",
        _0: "Something went wrong"
      },
      path: S$RescriptSchema.Path.empty
    });

var stringSchema = S$RescriptSchema.string;

export {
  stringSchema ,
  error ,
}
/* error Not a pure module */
