// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S_Core$RescriptStruct from "./S_Core.bs.mjs";

var Literal = S_Core$RescriptStruct.Literal;

var Path = S_Core$RescriptStruct.Path;

var Raised = S_Core$RescriptStruct.Raised;

var $$Error = S_Core$RescriptStruct.$$Error;

var never = S_Core$RescriptStruct.never;

var unknown = S_Core$RescriptStruct.unknown;

var unit = S_Core$RescriptStruct.unit;

var string = S_Core$RescriptStruct.string;

var bool = S_Core$RescriptStruct.bool;

var $$int = S_Core$RescriptStruct.$$int;

var $$float = S_Core$RescriptStruct.$$float;

var json = S_Core$RescriptStruct.json;

var literal = S_Core$RescriptStruct.literal;

var array = S_Core$RescriptStruct.array;

var list = S_Core$RescriptStruct.list;

var dict = S_Core$RescriptStruct.dict;

var option = S_Core$RescriptStruct.option;

var $$null = S_Core$RescriptStruct.$$null;

var jsonString = S_Core$RescriptStruct.jsonString;

var union = S_Core$RescriptStruct.union;

var $$catch = S_Core$RescriptStruct.$$catch;

var describe = S_Core$RescriptStruct.describe;

var description = S_Core$RescriptStruct.description;

var deprecate = S_Core$RescriptStruct.deprecate;

var deprecation = S_Core$RescriptStruct.deprecation;

var transform = S_Core$RescriptStruct.transform;

var preprocess = S_Core$RescriptStruct.preprocess;

var custom = S_Core$RescriptStruct.custom;

var refine = S_Core$RescriptStruct.refine;

var variant = S_Core$RescriptStruct.variant;

var parseWith = S_Core$RescriptStruct.parseWith;

var parseAnyWith = S_Core$RescriptStruct.parseAnyWith;

var parseJsonStringWith = S_Core$RescriptStruct.parseJsonStringWith;

var parseOrRaiseWith = S_Core$RescriptStruct.parseOrRaiseWith;

var parseAnyOrRaiseWith = S_Core$RescriptStruct.parseAnyOrRaiseWith;

var parseAsyncWith = S_Core$RescriptStruct.parseAsyncWith;

var parseAnyAsyncWith = S_Core$RescriptStruct.parseAnyAsyncWith;

var parseAsyncInStepsWith = S_Core$RescriptStruct.parseAsyncInStepsWith;

var parseAnyAsyncInStepsWith = S_Core$RescriptStruct.parseAnyAsyncInStepsWith;

var serializeWith = S_Core$RescriptStruct.serializeWith;

var serializeToUnknownWith = S_Core$RescriptStruct.serializeToUnknownWith;

var serializeToJsonStringWith = S_Core$RescriptStruct.serializeToJsonStringWith;

var serializeOrRaiseWith = S_Core$RescriptStruct.serializeOrRaiseWith;

var serializeToUnknownOrRaiseWith = S_Core$RescriptStruct.serializeToUnknownOrRaiseWith;

var isAsyncParse = S_Core$RescriptStruct.isAsyncParse;

var recursive = S_Core$RescriptStruct.recursive;

var classify = S_Core$RescriptStruct.classify;

var setName = S_Core$RescriptStruct.setName;

var $$Object = S_Core$RescriptStruct.$$Object;

var object = S_Core$RescriptStruct.object;

var Tuple = S_Core$RescriptStruct.Tuple;

var tuple = S_Core$RescriptStruct.tuple;

var tuple1 = S_Core$RescriptStruct.tuple1;

var tuple2 = S_Core$RescriptStruct.tuple2;

var tuple3 = S_Core$RescriptStruct.tuple3;

var $$Option = S_Core$RescriptStruct.$$Option;

var $$String = S_Core$RescriptStruct.$$String;

var Int = S_Core$RescriptStruct.Int;

var Float = S_Core$RescriptStruct.Float;

var $$Array = S_Core$RescriptStruct.$$Array;

var Metadata = S_Core$RescriptStruct.Metadata;

var inline = S_Core$RescriptStruct.inline;

export {
  Literal ,
  Path ,
  Raised ,
  $$Error ,
  never ,
  unknown ,
  unit ,
  string ,
  bool ,
  $$int ,
  $$float ,
  json ,
  literal ,
  array ,
  list ,
  dict ,
  option ,
  $$null ,
  jsonString ,
  union ,
  $$catch ,
  describe ,
  description ,
  deprecate ,
  deprecation ,
  transform ,
  preprocess ,
  custom ,
  refine ,
  variant ,
  parseWith ,
  parseAnyWith ,
  parseJsonStringWith ,
  parseOrRaiseWith ,
  parseAnyOrRaiseWith ,
  parseAsyncWith ,
  parseAnyAsyncWith ,
  parseAsyncInStepsWith ,
  parseAnyAsyncInStepsWith ,
  serializeWith ,
  serializeToUnknownWith ,
  serializeToJsonStringWith ,
  serializeOrRaiseWith ,
  serializeToUnknownOrRaiseWith ,
  isAsyncParse ,
  recursive ,
  classify ,
  setName ,
  $$Object ,
  object ,
  Tuple ,
  tuple ,
  tuple1 ,
  tuple2 ,
  tuple3 ,
  $$Option ,
  $$String ,
  Int ,
  Float ,
  $$Array ,
  Metadata ,
  inline ,
}
/* S_Core-RescriptStruct Not a pure module */
