import * as S_Js from "./S_JsApi.bs.mjs";

export const StructError = S_Js.RescriptStructError;
export const string = S_Js.string;
export const boolean = S_Js.$$boolean;
export const integer = S_Js.integer;
export const number = S_Js.number;
export const json = S_Js.json;
export const never = S_Js.never;
export const unknown = S_Js.unknown;
export const optional = S_Js.optional;
export const nullable = S_Js.nullable;
export const array = S_Js.array;
export const record = S_Js.record;
export const jsonString = S_Js.jsonString;
export const union = S_Js.union;
export const object = S_Js.$$Object.factory;
export const custom = S_Js.custom;
export const literal = S_Js.literal;
export const nan = S_Js.nan;
export const tuple = S_Js.tuple;
export const fail = S_Js.fail;
