// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";

let simpleObjectSchema = Sury.$schema(s => ({
  label: s.m(Sury.string),
  value: s.m(Sury.int32)
}));

Vitest$1.test("Simple object schema", t => {
  U.assertEqualSchemas(t, simpleObjectSchema, Sury.$schema(s => ({
    label: s.m(Sury.string),
    value: s.m(Sury.int32)
  })), undefined);
  Vitest.Assert.deepEqual(t, Sury.parseOrThrow({label:"foo",value:1}, simpleObjectSchema), {
    label: "foo",
    value: 1
  }, undefined);
});

export {
  simpleObjectSchema,
}
/* simpleObjectSchema Not a pure module */
