// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";

let variantSchema = Sury.union([
  Sury.literal("One"),
  Sury.literal("Two")
]);

Vitest$1.test("Variant", t => U.assertEqualSchemas(t, variantSchema, Sury.union([
  Sury.literal("One"),
  Sury.literal("Two")
]), undefined));

let variantWithSingleItemSchema = Sury.literal("Single");

Vitest$1.test("Variant with single item becomes a literal schema of the item", t => U.assertEqualSchemas(t, variantWithSingleItemSchema, Sury.literal("Single"), undefined));

let variantWithAliasSchema = Sury.union([
  Sury.literal("하나"),
  Sury.literal("Two")
]);

Vitest$1.test("Variant with partial @as usage", t => U.assertEqualSchemas(t, variantWithAliasSchema, Sury.union([
  Sury.literal("하나"),
  Sury.literal("Two")
]), undefined));

let variantWithPayloadsSchema = Sury.union([
  Sury.literal("Constant"),
  Sury.$schema(s => ({
    TAG: "SinglePayload",
    _0: s.m(Sury.int32)
  })),
  Sury.$schema(s => ({
    TAG: "TuplePayload",
    _0: s.m(Sury.int32),
    _1: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "RecordPayload",
    foo: s.m(Sury.number)
  }))
]);

Vitest$1.test("Variant with payloads", t => U.assertEqualSchemas(t, variantWithPayloadsSchema, Sury.union([
  Sury.literal("Constant"),
  Sury.$schema(s => ({
    TAG: "SinglePayload",
    _0: s.m(Sury.int32)
  })),
  Sury.$schema(s => ({
    TAG: "TuplePayload",
    _0: s.m(Sury.int32),
    _1: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "RecordPayload",
    foo: s.m(Sury.number)
  }))
]), undefined));

let unboxedVariantSchema = Sury.union([
  Sury.literal("Constant"),
  Sury.$schema(s => (s.m(Sury.int32))),
  Sury.$schema(s => (s.m(Sury.string)))
]);

Vitest$1.test("Unboxed variant", t => U.assertEqualSchemas(t, unboxedVariantSchema, Sury.union([
  Sury.literal("Constant"),
  Sury.$schema(s => (s.m(Sury.int32))),
  Sury.$schema(s => (s.m(Sury.string)))
]), undefined));

let taggedVariantSchema = Sury.union([
  Sury.$schema(s => ({
    kind: "circle",
    radius: s.m(Sury.number)
  })),
  Sury.$schema(s => ({
    kind: "square",
    x: s.m(Sury.number)
  })),
  Sury.$schema(s => ({
    kind: "triangle",
    x: s.m(Sury.number),
    y: s.m(Sury.number)
  }))
]);

Vitest$1.test("Tagged variant", t => U.assertEqualSchemas(t, taggedVariantSchema, Sury.union([
  Sury.$schema(s => ({
    kind: "circle",
    radius: s.m(Sury.number)
  })),
  Sury.$schema(s => ({
    kind: "square",
    x: s.m(Sury.number)
  })),
  Sury.$schema(s => ({
    kind: "triangle",
    x: s.m(Sury.number),
    y: s.m(Sury.number)
  }))
]), undefined));

let strictVariantSchema = Sury.strict(Sury.union([
  Sury.literal("StrictA"),
  Sury.$schema(s => ({
    TAG: "StrictB",
    _0: s.m(Sury.int32)
  }))
]));

let taggedInlinedAliasSchema = Sury.union([
  Sury.$schema(s => ({
    type: "Foo",
    Foo: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    type: "Bar",
    Bar: s.m(Sury.string)
  }))
]);

Vitest$1.test("@s.strict on root variant type", t => U.assertEqualSchemas(t, strictVariantSchema, Sury.strict(Sury.union([
  Sury.literal("StrictA"),
  Sury.$schema(s => ({
    TAG: "StrictB",
    _0: s.m(Sury.int32)
  }))
])), undefined));

Vitest$1.test("Tagged variant with inlined alias", t => U.assertEqualSchemas(t, taggedInlinedAliasSchema, Sury.union([
  Sury.$schema(s => ({
    type: "Foo",
    Foo: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    type: "Bar",
    Bar: s.m(Sury.string)
  }))
]), undefined));

let baseColorsSchema = Sury.union([
  Sury.literal("Red"),
  Sury.literal("Blue"),
  Sury.literal("Green")
]);

let extendedColorsSchema = Sury.union([Sury.literal("Yellow")].concat(baseColorsSchema.type === "anyOf" ? baseColorsSchema.anyOf : [baseColorsSchema]));

Vitest$1.test("Variant with type spread", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow("Red", extendedColorsSchema), "Red", undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow("Yellow", extendedColorsSchema), "Yellow", undefined);
  U.assertReverseReversesBack(t, extendedColorsSchema);
});

let singleCaseSchema = Sury.literal("Only");

let extendedFromSingleCaseSchema = Sury.union([Sury.literal("Another")].concat(singleCaseSchema.type === "anyOf" ? singleCaseSchema.anyOf : [singleCaseSchema]));

Vitest$1.test("Variant spread of a single-case (literal) schema", t => {
  Vitest.Assert.deepEqual(t, S.parseOrThrow("Only", extendedFromSingleCaseSchema), "Only", undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow("Another", extendedFromSingleCaseSchema), "Another", undefined);
  U.assertReverseReversesBack(t, extendedFromSingleCaseSchema);
});

export {
  variantSchema,
  variantWithSingleItemSchema,
  variantWithAliasSchema,
  variantWithPayloadsSchema,
  unboxedVariantSchema,
  taggedVariantSchema,
  strictVariantSchema,
  taggedInlinedAliasSchema,
  baseColorsSchema,
  extendedColorsSchema,
  singleCaseSchema,
  extendedFromSingleCaseSchema,
}
/* variantSchema Not a pure module */
