// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "vitest";

let myStringSchema = Sury.string;

Vitest.test("String schema", t => U.assertEqualSchemas(t, myStringSchema, Sury.string, undefined));

let myIntSchema = Sury.int32;

Vitest.test("Int schema", t => U.assertEqualSchemas(t, myIntSchema, Sury.int32, undefined));

let myFloatSchema = Sury.number;

Vitest.test("Float schema", t => U.assertEqualSchemas(t, myFloatSchema, Sury.number, undefined));

let myBoolSchema = Sury.boolean;

Vitest.test("Bool schema", t => U.assertEqualSchemas(t, myBoolSchema, Sury.boolean, undefined));

let myUnitSchema = Sury.$unit;

Vitest.test("Unit schema", t => U.assertEqualSchemas(t, myUnitSchema, Sury.$unit, undefined));

let myUnknownSchema = Sury.unknown;

Vitest.test("Unknown schema", t => U.assertEqualSchemas(t, myUnknownSchema, Sury.unknown, undefined));

let myNeverSchema = Sury.never;

Vitest.test("Never schema", t => U.assertEqualSchemas(t, myNeverSchema, Sury.never, undefined));

let myOptionOfStringSchema = Sury.$option(Sury.string);

Vitest.test("Option of string schema", t => U.assertEqualSchemas(t, myOptionOfStringSchema, Sury.$option(Sury.string), undefined));

let myNullableOfStringSchema = Sury.nullish(Sury.string);

Vitest.test("Nullable of string schema", t => U.assertEqualSchemas(t, myNullableOfStringSchema, Sury.nullish(Sury.string), undefined));

let myArrayOfStringSchema = Sury.array(Sury.string);

Vitest.test("Array of string schema", t => U.assertEqualSchemas(t, myArrayOfStringSchema, Sury.array(Sury.string), undefined));

let myListOfStringSchema = Sury.list(Sury.string);

Vitest.test("List of string schema", t => U.assertEqualSchemas(t, myListOfStringSchema, Sury.list(Sury.string), undefined));

let myDictOfStringSchema = Sury.record(Sury.string);

Vitest.test("Dict of string schema", t => U.assertEqualSchemas(t, myDictOfStringSchema, Sury.record(Sury.string), undefined));

let myDictOfStringFromJsSchema = Sury.record(Sury.string);

Vitest.test("Dict of string schema from Js", t => U.assertEqualSchemas(t, myDictOfStringSchema, Sury.record(Sury.string), undefined));

let myDictOfStringFromCoreSchema = Sury.record(Sury.string);

Vitest.test("Dict of string schema from Core", t => U.assertEqualSchemas(t, myDictOfStringFromCoreSchema, Sury.record(Sury.string), undefined));

let myJsonSchema = Sury.json;

Vitest.test("Json schema", t => U.assertEqualSchemas(t, myJsonSchema, Sury.json, undefined));

let myJsonFromCoreSchema = Sury.json;

Vitest.test("Json schema from Core", t => U.assertEqualSchemas(t, myJsonFromCoreSchema, Sury.json, undefined));

let myTupleSchema = Sury.$schema(s => [
  s.m(Sury.string),
  s.m(Sury.int32)
]);

Vitest.test("Tuple schema", t => U.assertEqualSchemas(t, myTupleSchema, S.tuple2(Sury.string, Sury.int32), undefined));

let myBigTupleSchema = Sury.$schema(s => [
  s.m(Sury.string),
  s.m(Sury.string),
  s.m(Sury.string),
  s.m(Sury.int32),
  s.m(Sury.int32),
  s.m(Sury.int32),
  s.m(Sury.number),
  s.m(Sury.number),
  s.m(Sury.number),
  s.m(Sury.boolean),
  s.m(Sury.boolean),
  s.m(Sury.boolean)
]);

Vitest.test("Big tuple schema", t => U.assertEqualSchemas(t, myBigTupleSchema, Sury.$schema(s => [
  s.m(Sury.string),
  s.m(Sury.string),
  s.m(Sury.string),
  s.m(Sury.int32),
  s.m(Sury.int32),
  s.m(Sury.int32),
  s.m(Sury.number),
  s.m(Sury.number),
  s.m(Sury.number),
  s.m(Sury.boolean),
  s.m(Sury.boolean),
  s.m(Sury.boolean)
]), undefined));

let myCustomSchema = Sury.trim(Sury.string);

Vitest.test("Custom string schema", t => U.assertEqualSchemas(t, myCustomSchema, myCustomSchema, undefined));

let myCustomLiteralStringSchema = Sury.literal("123");

Vitest.test("Custom litaral string schema", t => U.assertEqualSchemas(t, myCustomLiteralStringSchema, Sury.literal("123"), undefined));

let myCustomOptionalStringSchema = Sury.$option(myCustomSchema);

Vitest.test("Custom optional string schema", t => U.assertEqualSchemas(t, myCustomOptionalStringSchema, Sury.$option(myCustomSchema), undefined));

let myNullOfStringSchema = Sury.$nullAsOption(Sury.string);

Vitest.test("Null of string schema", t => U.assertEqualSchemas(t, myNullOfStringSchema, Sury.$nullAsOption(Sury.string), undefined));

let myCustomStringSchema = myCustomSchema;

export {
  myStringSchema,
  myIntSchema,
  myFloatSchema,
  myBoolSchema,
  myUnitSchema,
  myUnknownSchema,
  myNeverSchema,
  myOptionOfStringSchema,
  myNullableOfStringSchema,
  myArrayOfStringSchema,
  myListOfStringSchema,
  myDictOfStringSchema,
  myDictOfStringFromJsSchema,
  myDictOfStringFromCoreSchema,
  myJsonSchema,
  myJsonFromCoreSchema,
  myTupleSchema,
  myBigTupleSchema,
  myCustomSchema,
  myCustomStringSchema,
  myCustomLiteralStringSchema,
  myCustomOptionalStringSchema,
  myNullOfStringSchema,
}
/* myStringSchema Not a pure module */
