// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "../utils/Vitest.res.mjs";
import * as Vitest$1 from "vitest";

let myEmailSchema = Sury.email;

Vitest$1.test("Email schema", t => U.assertEqualSchemas(t, myEmailSchema, Sury.email, undefined));

let myPortSchema = Sury.port;

Vitest$1.test("Port schema", t => U.assertEqualSchemas(t, myPortSchema, Sury.port, undefined));

let myIntegerSchema = Sury.integer;

Vitest$1.test("Integer schema", t => U.assertEqualSchemas(t, myIntegerSchema, Sury.integer, undefined));

let myJsonStringSchema = Sury.jsonString;

Vitest$1.test("JsonString schema", t => U.assertEqualSchemas(t, myJsonStringSchema, Sury.jsonString, undefined));

let myUrlSchema = Sury.url;

Vitest$1.test("Url schema", t => U.assertEqualSchemas(t, myUrlSchema, Sury.url, undefined));

let myDateSchema = Sury.date;

Vitest$1.test("Date schema", t => U.assertEqualSchemas(t, myDateSchema, Sury.date, undefined));

let myBlobSchema = Sury.blob;

Vitest$1.test("Blob schema", t => U.assertEqualSchemas(t, myBlobSchema, Sury.blob, undefined));

let myNonEmptyTagsSchema = Sury.nonEmpty(Sury.array(Sury.string));

Vitest$1.test("NonEmpty schema", t => U.assertEqualSchemas(t, myNonEmptyTagsSchema, Sury.nonEmpty(Sury.array(Sury.string)), undefined));

let userSchema = Sury.$schema(s => ({
  id: s.m(Sury.uuid),
  email: s.m(Sury.email),
  tags: s.m(Sury.nonEmpty(Sury.array(Sury.string))),
  homepage: s.m(Sury.$option(Sury.uri))
}));

Vitest$1.test("Record of formats", t => {
  U.assertEqualSchemas(t, userSchema, Sury.$schema(s => ({
    id: s.m(Sury.uuid),
    email: s.m(Sury.email),
    tags: s.m(Sury.nonEmpty(Sury.array(Sury.string))),
    homepage: s.m(Sury.$option(Sury.uri))
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({id: "123e4567-e89b-12d3-a456-426614174000", email: "a@b.com", tags: ["x"]}, userSchema), {
    id: "123e4567-e89b-12d3-a456-426614174000",
    email: "a@b.com",
    tags: ["x"],
    homepage: undefined
  }, undefined);
});

let identifiersSchema = Sury.$schema(s => ({
  key: s.m(Sury.uuidv7),
  legacyKey: s.m(Sury.uuid),
  slug: s.m(Sury.cuid2),
  event: s.m(Sury.ulid),
  trace: s.m(Sury.xid),
  token: s.m(Sury.nanoid)
}));

Vitest$1.test("Record of id formats", t => U.assertEqualSchemas(t, identifiersSchema, Sury.$schema(s => ({
  key: s.m(Sury.uuidv7),
  legacyKey: s.m(Sury.uuid),
  slug: s.m(Sury.cuid2),
  event: s.m(Sury.ulid),
  trace: s.m(Sury.xid),
  token: s.m(Sury.nanoid)
})), undefined));

let hostSchema = Sury.$schema(s => ({
  block: s.m(Sury.cidrv4),
  address: s.m(Sury.ipv4),
  hardware: s.m(Sury.mac),
  homepage: s.m(Sury.httpUrl),
  phone: s.m(Sury.e164),
  digest: s.m(Sury.hex)
}));

Vitest$1.test("Record of network formats", t => {
  U.assertEqualSchemas(t, hostSchema, Sury.$schema(s => ({
    block: s.m(Sury.cidrv4),
    address: s.m(Sury.ipv4),
    hardware: s.m(Sury.mac),
    homepage: s.m(Sury.httpUrl),
    phone: s.m(Sury.e164),
    digest: s.m(Sury.hex)
  })), undefined);
  Vitest.Assert.deepEqual(t, S.parseOrThrow({
      block: "192.168.0.0/16",
      address: "192.168.0.1",
      hardware: "00:1b:44:11:3a:b7",
      homepage: "https://example.com",
      phone: "+14155552671",
      digest: "deadbeef"
    }, hostSchema), {
    block: "192.168.0.0/16",
    address: "192.168.0.1",
    hardware: "00:1b:44:11:3a:b7",
    homepage: "https://example.com",
    phone: "+14155552671",
    digest: "deadbeef"
  }, undefined);
});

export {
  myEmailSchema,
  myPortSchema,
  myIntegerSchema,
  myJsonStringSchema,
  myUrlSchema,
  myDateSchema,
  myBlobSchema,
  myNonEmptyTagsSchema,
  userSchema,
  identifiersSchema,
  hostSchema,
}
/* myEmailSchema Not a pure module */
