// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "vitest";

let schema = Sury.string;

Vitest.test("Creates schema with the name schema from t type", t => U.assertEqualSchemas(t, schema, Sury.string, undefined));

let fooSchema = Sury.int;

Vitest.test("Creates schema with the type name and schema at the for non t types", t => U.assertEqualSchemas(t, fooSchema, Sury.int, undefined));

let reusedTypesSchema = Sury.$schema(s => [
  s.m(schema),
  s.m(fooSchema),
  s.m(Sury.bool),
  s.m(Sury.float)
]);

Vitest.test("Can reuse schemas from other types", t => U.assertEqualSchemas(t, reusedTypesSchema, Sury.$schema(s => [
  s.m(schema),
  s.m(fooSchema),
  s.m(Sury.bool),
  s.m(Sury.float)
]), undefined));

let stringWithDefaultSchema = Sury.$Option_getOr(Sury.$option(Sury.string), "Foo");

Vitest.test("Creates schema with default", t => U.assertEqualSchemas(t, stringWithDefaultSchema, Sury.$Option_getOr(Sury.$option(Sury.string), "Foo"), undefined));

let myCustomSchema = Sury.trim(Sury.string);

let stringWithDefaultAndMatchesSchema = Sury.$Option_getOr(Sury.$option(myCustomSchema), "https://example.com");

Vitest.test("Creates schema with default using @s.matches", t => U.assertEqualSchemas(t, stringWithDefaultAndMatchesSchema, Sury.$Option_getOr(Sury.$option(myCustomSchema), "https://example.com"), undefined));

let stringWithDefaultNullAndMatchesSchema = Sury.$Option_getOr(Sury.$nullAsOption(myCustomSchema), "https://example.com");

Vitest.test("Creates schema with default null using @s.matches", t => U.assertEqualSchemas(t, stringWithDefaultNullAndMatchesSchema, Sury.$Option_getOr(Sury.$nullAsOption(myCustomSchema), "https://example.com"), undefined));

let ignoredNullWithMatchesSchema = Sury.$option(Sury.string);

Vitest.test("@s.null doesn't override @s.matches(S.option(_))", t => U.assertEqualSchemas(t, ignoredNullWithMatchesSchema, Sury.$option(Sury.string), undefined));

let stringWithWithSchema = Sury.trim(Sury.string);

Vitest.test("Creates schema with @s.with transform", t => U.assertEqualSchemas(t, stringWithWithSchema, Sury.trim(Sury.string), undefined));

let stringWithMultipleWithSchema = Sury.maxLength(Sury.minLength(Sury.trim(Sury.string), 1), 5);

Vitest.test("Applies multiple @s.with transforms in order of appearance", t => U.assertEqualSchemas(t, stringWithMultipleWithSchema, Sury.maxLength(Sury.minLength(Sury.trim(Sury.string), 1), 5), undefined));

let userWithWithSchema = Sury.meta(Sury.$schema(s => ({
  name: s.m(Sury.length(Sury.string, 2)),
  age: s.m(Sury.gte(Sury.int, 18))
})), {
  description: "A user"
});

Vitest.test("Applies @s.with on type declaration and on fields of different types", t => U.assertEqualSchemas(t, userWithWithSchema, Sury.meta(Sury.$schema(s => ({
  name: s.m(Sury.length(Sury.string, 2)),
  age: s.m(Sury.gte(Sury.int, 18))
})), {
  description: "A user"
}), undefined));

let stringWithDefaultAndWithSchema = Sury.trim(Sury.$Option_getOr(Sury.$option(Sury.string), "Foo"));

Vitest.test("Combines @s.with with @s.default", t => U.assertEqualSchemas(t, stringWithDefaultAndWithSchema, Sury.trim(Sury.$Option_getOr(Sury.$option(Sury.string), "Foo")), undefined));

let stringWithWithAndDefaultSchema = Sury.$Option_getOr(Sury.$option(Sury.trim(Sury.string)), "Foo");

Vitest.test("Combines @s.with written before @s.default", t => U.assertEqualSchemas(t, stringWithWithAndDefaultSchema, Sury.$Option_getOr(Sury.$option(Sury.trim(Sury.string)), "Foo"), undefined));

let intWithWithPlaceholderSchema = Sury.lte(Sury.gte(Sury.int, 1), 5);

Vitest.test("Applies @s.with with partial application placeholder", t => U.assertEqualSchemas(t, intWithWithPlaceholderSchema, Sury.lte(Sury.gte(Sury.int, 1), 5), undefined));

let recordWithOptionalWithFieldSchema = Sury.$schema(s => ({
  maybe: s.m(Sury.$option(Sury.trim(Sury.string)))
}));

Vitest.test("Applies @s.with on an optional field", t => U.assertEqualSchemas(t, recordWithOptionalWithFieldSchema, Sury.$schema(s => ({
  maybe: s.m(Sury.$option(Sury.trim(Sury.string)))
})), undefined));

function paramWithWithSchema(_sWith1Schema) {
  return Sury.meta(Sury.array(_sWith1Schema), {
    description: "wrapped"
  });
}

Vitest.test("Applies @s.with on a parametrized type", t => U.assertEqualSchemas(t, paramWithWithSchema(Sury.string), Sury.meta(Sury.array(Sury.string), {
  description: "wrapped"
}), undefined));

let withOverNestedAttributesSchema = Sury.meta(Sury.array(Sury.$Option_getOr(Sury.$option(Sury.string), "x")), {
  description: "items"
});

Vitest.test("Applies @s.with over a nested @s.default", t => U.assertEqualSchemas(t, withOverNestedAttributesSchema, Sury.meta(Sury.array(Sury.$Option_getOr(Sury.$option(Sury.string), "x")), {
  description: "items"
}), undefined));

export {
  schema,
  fooSchema,
  reusedTypesSchema,
}
/* schema Not a pure module */
