// Generated by ReScript, PLEASE EDIT WITH CARE

import * as U from "../utils/U.res.mjs";
import * as Sury from "sury";
import * as Vitest from "vitest";

let ratingSchema = Sury.union([
  Sury.literal("G"),
  Sury.literal("PG"),
  Sury.literal("PG13"),
  Sury.literal("R")
]);

let filmSchema = Sury.$schema(s => ({
  Id: s.m(Sury.float),
  Title: s.m(Sury.string),
  Tags: s.m(Sury.$Option_getOr(Sury.$option(Sury.array(Sury.string)), [])),
  Rating: s.m(ratingSchema),
  Age: s.m(Sury.meta(Sury.$option(Sury.int), {
    description: "Use rating instead",
    deprecated: true
  }))
}));

Vitest.test("Main example", t => U.assertEqualSchemas(t, filmSchema, Sury.$schema(s => ({
  Id: s.m(Sury.float),
  Title: s.m(Sury.string),
  Tags: s.m(Sury.$Option_getOr(Sury.$option(Sury.array(Sury.string)), [])),
  Rating: s.m(Sury.union([
    Sury.literal("G"),
    Sury.literal("PG"),
    Sury.literal("PG13"),
    Sury.literal("R")
  ])),
  Age: s.m(Sury.meta(Sury.$option(Sury.int), {
    description: "Use rating instead",
    deprecated: true
  }))
})), undefined));

let myCustomSchema = Sury.maxLength(Sury.string, 5);

Vitest.test("@s.matches", t => U.assertEqualSchemas(t, myCustomSchema, myCustomSchema, undefined));

let urlSchema = Sury.url;

Vitest.test("Format schema as a type", t => U.assertEqualSchemas(t, urlSchema, Sury.url, undefined));

let defaultSchema = Sury.$Option_getOr(Sury.$option(Sury.string), "Unknown");

Vitest.test("@s.default", t => U.assertEqualSchemas(t, defaultSchema, Sury.$Option_getOr(Sury.$option(Sury.string), "Unknown"), undefined));

let defaultWithSchema = Sury.$Option_getOrWith(Sury.$option(Sury.array(Sury.string)), () => []);

Vitest.test("@s.defaultWith", t => U.assertEqualSchemas(t, defaultWithSchema, Sury.$Option_getOrWith(Sury.$option(Sury.array(Sury.string)), () => []), undefined));

let nullSchema = Sury.$nullAsOption(Sury.string);

Vitest.test("@s.null", t => U.assertEqualSchemas(t, nullSchema, Sury.$nullAsOption(Sury.string), undefined));

let nullWithDefaultSchema = Sury.$Option_getOr(Sury.$nullAsOption(Sury.string), "Unknown");

Vitest.test("@s.null with @s.default", t => U.assertEqualSchemas(t, nullWithDefaultSchema, Sury.$Option_getOr(Sury.$nullAsOption(Sury.string), "Unknown"), undefined));

let nullableSchema = Sury.$nullableAsOption(Sury.string);

Vitest.test("@s.nullable", t => U.assertEqualSchemas(t, nullableSchema, Sury.$nullableAsOption(Sury.string), undefined));

let nullableWithDefaultSchema = Sury.$Option_getOr(Sury.$nullableAsOption(Sury.string), "Unknown");

Vitest.test("@s.nullable with @s.default", t => U.assertEqualSchemas(t, nullableWithDefaultSchema, Sury.$Option_getOr(Sury.$nullableAsOption(Sury.string), "Unknown"), undefined));

let deprecatedSchema = Sury.meta(Sury.string, {
  description: "Will be removed in APIv2",
  deprecated: true
});

Vitest.test("@s.deprecated", t => U.assertEqualSchemas(t, deprecatedSchema, Sury.meta(Sury.string, {
  description: "Will be removed in APIv2",
  deprecated: true
}), undefined));

let describeSchema = Sury.meta(Sury.string, {
  description: "A useful bit of text, if you know what to do with it."
});

Vitest.test("@s.description", t => U.assertEqualSchemas(t, describeSchema, Sury.meta(Sury.string, {
  description: "A useful bit of text, if you know what to do with it."
}), undefined));

let matchesSchema = myCustomSchema;

export {
  ratingSchema,
  filmSchema,
  myCustomSchema,
  matchesSchema,
  urlSchema,
  defaultSchema,
  defaultWithSchema,
  nullSchema,
  nullWithDefaultSchema,
  nullableSchema,
  nullableWithDefaultSchema,
  deprecatedSchema,
  describeSchema,
}
/* ratingSchema Not a pure module */
